### PR TITLE
Make Java cryptographic strength configurable

### LINKED ISSUE #118: Kind request to include Java8 unlimited JCE policy extension into openhab docker image
Hi there,
first of all thank you for providing an official openhab docker image!!!
I experience an issue with the binding for my heating (Buderus KM200) that requires the Java8 extension for unlimited JCE policy to allow longer hashes for password strings to be able to read and decode the data coming from the gateway. Probably this issue does not only affect me with the KM200 binding but also other bindings that use today resp. will use in the future longer hash strings for authentication as supported with the standard version of Java.
Even though JCE is included in the docker image it does not work correctly. Please find below the error I get in the openhab.log:

> 22:54:07.169 [INFO ] [.binding.km200.internal.KM200Binding] - Update KM200 Binding configuration, it takes a minute....
> 2017-10-30 22:54:07.178 [INFO ] [.binding.km200.internal.KM200Binding] - Starting communication test..
> 2017-10-30 22:54:07.446 [INFO ] [.binding.km200.internal.KM200Binding] - Received data..
> 2017-10-30 22:54:07.460 [ERROR] [hab.binding.km200.internal.KM200Comm] - Exception on encoding: {}
> java.security.InvalidKeyException: Illegal key size or default parameters
> 	at javax.crypto.Cipher.checkCryptoPerm(Cipher.java:1026)[:1.8.0_144]
> 	at javax.crypto.Cipher.implInit(Cipher.java:801)[:1.8.0_144]
> 	at javax.crypto.Cipher.chooseProvider(Cipher.java:864)[:1.8.0_144]
> 	at javax.crypto.Cipher.init(Cipher.java:1249)[:1.8.0_144]
> 	at javax.crypto.Cipher.init(Cipher.java:1186)[:1.8.0_144]
> 	at org.openhab.binding.km200.internal.KM200Comm.decodeMessage(KM200Comm.java:260)[183:org.openhab.binding.km200:1.10.0]
> 	at org.openhab.binding.km200.internal.KM200Binding.updated(KM200Binding.java:161)[183:org.openhab.binding.km200:1.10.0]
> 	at org.apache.felix.cm.impl.helper.ManagedServiceTracker.updated(ManagedServiceTracker.java:189)[3:org.apache.felix.configadmin:1.8.12]
> 	at org.apache.felix.cm.impl.helper.ManagedServiceTracker.updateService(ManagedServiceTracker.java:152)[3:org.apache.felix.configadmin:1.8.12]
> 	at org.apache.felix.cm.impl.helper.ManagedServiceTracker.provideConfiguration(ManagedServiceTracker.java:85)[3:org.apache.felix.configadmin:1.8.12]
> 	at org.apache.felix.cm.impl.ConfigurationManager$ManagedServiceUpdate.provide(ConfigurationManager.java:1461)[3:org.apache.felix.configadmin:1.8.12]
> 	at org.apache.felix.cm.impl.ConfigurationManager$ManagedServiceUpdate.run(ConfigurationManager.java:1417)[3:org.apache.felix.configadmin:1.8.12]
> 	at org.apache.felix.cm.impl.UpdateThread.run0(UpdateThread.java:141)[3:org.apache.felix.configadmin:1.8.12]
> 	at org.apache.felix.cm.impl.UpdateThread.run(UpdateThread.java:109)[3:org.apache.felix.configadmin:1.8.12]
> 	at java.lang.Thread.run(Thread.java:748)[:1.8.0_144]
> 2017-10-30 22:54:07.466 [ERROR] [org.apache.felix.configadmin        ] - [org.osgi.service.cm.ManagedService, org.osgi.service.event.EventHandler, id=292, bundle=183/mvn:org.openhab.binding/org.openhab.binding.km200/1.10.0]: Unexpected problem updating configuration org.openhab.km200
> java.lang.RuntimeException: Decoding of the KM200 message is not possible!
> 	at org.openhab.binding.km200.internal.KM200Binding.updated(KM200Binding.java:163)[183:org.openhab.binding.km200:1.10.0]
> 	at org.apache.felix.cm.impl.helper.ManagedServiceTracker.updated(ManagedServiceTracker.java:189)[3:org.apache.felix.configadmin:1.8.12]
> 	at org.apache.felix.cm.impl.helper.ManagedServiceTracker.updateService(ManagedServiceTracker.java:152)[3:org.apache.felix.configadmin:1.8.12]
> 	at org.apache.felix.cm.impl.helper.ManagedServiceTracker.provideConfiguration(ManagedServiceTracker.java:85)[3:org.apache.felix.configadmin:1.8.12]
> 	at org.apache.felix.cm.impl.ConfigurationManager$ManagedServiceUpdate.provide(ConfigurationManager.java:1461)[3:org.apache.felix.configadmin:1.8.12]
> 	at org.apache.felix.cm.impl.ConfigurationManager$ManagedServiceUpdate.run(ConfigurationManager.java:1417)[3:org.apache.felix.configadmin:1.8.12]
> 	at org.apache.felix.cm.impl.UpdateThread.run0(UpdateThread.java:141)[3:org.apache.felix.configadmin:1.8.12]
> 	at org.apache.felix.cm.impl.UpdateThread.run(UpdateThread.java:109)[3:org.apache.felix.configadmin:1.8.12]
> 	at java.lang.Thread.run(Thread.java:748)[:1.8.0_144]
> 

I did some research what is needed for JCE and found the following to JAR files need to be installed in the docker image. The files are called **local_policy.jar** and **US_export_policy.jar** and they are in the image as shown below:

> root@openhab-openhab220:/usr/lib/java-8/jre/lib/security# ls -l
> total 236
> -rw-rw-r-- 1 31450 31450 1273 Jul 26 14:24 blacklisted.certs
> -rw-rw-r-- 1 31450 31450 186962 Jul 26 14:24 cacerts
> -rw-rw-r-- 1 31450 31450 2466 Jul 26 14:24 java.policy
> -rw-rw-r-- 1 31450 31450 34688 Jul 26 14:24 java.security
> -rw-rw-r-- 1 31450 31450 1040 Jul 26 14:24 local_policy.jar
> -rw-rw-r-- 1 31450 31450 620 Jul 26 14:24 US_export_policy.jar
> root@openhab-openhab220:/usr/lib/java-8/jre/lib/security#

I don't get errors and it works with the wetware/openhab docker image which uses OpenJDK 1.8.0.45 with JCE and the JDK used in your official openhab image is 1.8.0_144 and has also the JCE files. Hence there must be the difference in the Java versions and/or probably in the Java default configuration.

I would prefer much more to use your official image as some cloned one.
Hence I kindly ask you to consider my issue!

### PR DESCRIPTION
**Pull request by wborn**
* Use limited strength in debian and alpine containers by default
* Add CRYPTO_POLICY environment variable to install unlimited strength on first start when value is set to "unlimited"
* Update documentation

Fixes #118

Ready for review by @cniweb, @martinvw, @smerschjohann, @rkoshak

---
This change is [Reviewable](https://reviewable.io/reviews/openhab/openhab-docker/154)

### CODE REVIEW

**Comment by wborn** [comment]
An easy way to check if you have limited or unlimited cryptography is by executing the following command in the container:

`$JAVA_HOME/bin/jrunscript -e 'print (javax.crypto.Cipher.getMaxAllowedKeyLength("AES"));'`

It will return:
* 128 when limited
* 2147483647 when unlimited

**Comment by cniweb** [comment]
Reviewed 84 of 84 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/openhab/openhab-docker/154)*

**Comment by cniweb** [comment]
:lgtm:

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/openhab/openhab-docker/154#-:-L2bTPet-7hPYCcQCvAm:bnfp4nl)*

File: entrypoint_alpine.sh [hunk 1]
```diff
@@ -10,6 +10,14 @@ fi
 set -euo pipefail
 IFS=$'\n\t'
 
+# Install Java unlimited strength cryptography
+if [ "${CRYPTO_POLICY}" = "unlimited" ] && [ ! -d "${JAVA_HOME}/jre/lib/security/policy/unlimited" ]; then
+echo "Installing OpenJDK unlimited strength cryptography policy..."
+  apk update
```
Comment (martinvw) [inline entrypoint_alpine.sh]: This update is not needed if you use `--no-cache`, see https://github.com/gliderlabs/docker-alpine/blob/master/docs/usage.md#disabling-cache

File: entrypoint_alpine.sh [hunk 2]
```diff
@@ -10,6 +10,14 @@ fi
...
+  apk fix --no-cache openjdk8-jre-lib
+  rm -rf /var/cache/apk/*
```
Comment (martinvw) [inline entrypoint_alpine.sh]: This is also not needed if you use `--no-cache`

File: update.sh [hunk 3]
```diff
@@ -91,9 +91,10 @@ print_basemetadata() {
 	    EXTRA_JAVA_OPTS="" \
 	    OPENHAB_HTTP_PORT="8080" \
 	    OPENHAB_HTTPS_PORT="8443" \
-	    LC_ALL=en_US.UTF-8 \
-	    LANG=en_US.UTF-8 \
-	    LANGUAGE=en_US.UTF-8
+	    LC_ALL="en_US.UTF-8" \
+	    LANG="en_US.UTF-8" \
+	    LANGUAGE="en_US.UTF-8" \
+	    CRYPTO_POLICY="limited"
```
Comment (martinvw) [inline update.sh]: Would a boolean like thing make more sense, it feels a little bit error prone?

Comment (martinvw) [reply update.sh]: Maybe we can let something fail if its neither limited or unlimited?

File: entrypoint_alpine.sh (hunk 1 above)
Comment (martinvw) [reply entrypoint_alpine.sh]: But I'm not 100% sure whether that is only for add or also for fix

File: update.sh (hunk 3 above)
Comment (cniweb) [reply update.sh]: I also think that a boolean parameter is better.

File: entrypoint_alpine.sh (hunk 1 above)
Comment (wborn) [reply entrypoint_alpine.sh]: The update is required for downloading the package index which is removed during the build. Without it you can not operate on packages.

File: entrypoint_alpine.sh (hunk 2 above)
Comment (wborn) [reply entrypoint_alpine.sh]: It is there to remove the package index from `/var/cache/apk`.

File: entrypoint_alpine.sh (hunk 1 above)
Comment (martinvw) [reply entrypoint_alpine.sh]: Citing from above link:
> This avoids the need to use --update and remove /var/cache/apk/* when done installing packages.

And I just tested it:

```shell
/ # apk fix --no-cache git
fetch http://dl-cdn.alpinelinux.org/alpine/v3.7/main/x86_64/APKINDEX.tar.gz
fetch http://dl-cdn.alpinelinux.org/alpine/v3.7/community/x86_64/APKINDEX.tar.gz
(1/1) Reinstalling git (2.15.0-r1)
Executing busybox-1.27.2-r6.trigger
OK: 22 MiB in 19 packages
/ # ls -la /var/cache/apk/
total 8
drwxr-xr-x    2 root     root          4096 Dec  1 16:32 .
drwxr-xr-x    6 root     root          4096 Jan 12 08:51 ..
/ #
```

File: update.sh (hunk 3 above)
Comment (wborn) [reply update.sh]: I've thought about using a boolean as well but then found out how Java handles this with policies so opted for using name and values closely related to this mechanism. It looks like Oracle and OpenJDK also allow for other policies besides just "limited" and "unlimited". 

When using a boolean the variable name should  also change. Any suggestions for this? It should be short, meaningful and independent of the JVM used in the container.

Comment (cniweb) [reply update.sh]: OK, if Oracle and OpenJDK use the values "limited" and "unlimited" we should do that as well.

Comment (martinvw) [reply update.sh]: > martinvw 9 hours ago  Member
Maybe we can let something fail if its neither limited or unlimited?

@wborn wdyt?

Comment (wborn) [reply update.sh]: I thought about that too but did not implement it to keep it simple also because there were no checks for the [other environment variables](https://github.com/openhab/openhab-docker#environment-variables).

**Comment by martinvw** [comment]
Lets start out simple then, if questions arrive we can always implement something like you did for the tty

**Comment by cniweb** [comment]
Reviewed 21 of 21 files at r2.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/openhab/openhab-docker/154)*
